name: pythonWorkflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          python hello.py
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkedout@v3
      - run: python hello.py
  
